[package]
name = "minigrep"
description = "A light version of the popular command-line utility `grep`"
license = "MIT"
version = "0.1.0"
authors = ["AlexandruGG <alex.gidei@goodlord.co>"]
repository = "https://github.com/AlexandruGG/minigrep-rust"
edition = "2018"

[dependencies]
